### ISSUE TITLE
Migrate to GitHub actions

### ISSUE THREAD

**Issue by mhutter** [mhutter/ansible-docker-systemd-service#41]
- [x] Run `yamllint`
- [x] Do an Ansible syntax check
- [ ] Ping Ansible Galaxy on new tags
- [x] Bonus: Generate Changelog from Pull Requests on Github using something like mikepenz/release-changelog-builder-action

See old `travis.yml`:

https://github.com/mhutter/ansible-docker-systemd-service/blob/3b8da4bbc840c542ef0d46815890ad58a5e17cc8/.travis.yml

**Comment by rishvantsingh** [comment]
Ill write githubactions for the following repo.
